# -*- coding: utf-8 -*-
"""BigDataProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhFszLMRrYmcIQ4cbx1VpskIdEyY7W3E
"""

#북극/남극 해빙 변화 10년 데이터

import pandas as pd
import glob


df_n = pd.read_csv("/content/N_09_extent_v4.0.csv")
df_n = df_n.replace(-9999, pd.NA)

latest_year_n = df_n["year"].max()
start_year_n = latest_year_n - 10

last10_n = df_n[(df_n["year"] >= start_year_n) & (df_n["year"] <= latest_year_n)]

yearly_n = df_n.groupby(["year"," region"])[" extent"].mean().reset_index()
yearly_n

#남극
file_list_s = glob.glob("/content/South/*.csv")

dfs_s = []

for file in file_list_s:
    df_s = pd.read_csv(file)
    df_s = df_s.replace(-9999, pd.NA)
    dfs_s.append(df_s)

full_df_s = pd.concat(dfs_s, ignore_index=True)
full_df_s = full_df_s.sort_values(by=["year", " mo"]).reset_index(drop=True)

latest_year_s = full_df_s["year"].max()
start_year_s = latest_year_s - 10

last10_s = full_df_s[(full_df_s["year"] >= start_year_s) & (full_df_s["year"] <= latest_year_s)]

last10_s.head(), last10_s.tail()

yearly_s = full_df_s.groupby(["year"," region"])[" extent"].mean().reset_index()
yearly_s

import plotly.graph_objects as go
from plotly.subplots import make_subplots

yearly_n = yearly_n.rename(columns=lambda x: x.strip())
yearly_s = yearly_s.rename(columns=lambda x: x.strip())

yearly_n["region"] = yearly_n["region"].astype(str).str.strip().str.upper()
yearly_s["region"] = yearly_s["region"].astype(str).str.strip().str.upper()

yearly_n["extent"] = pd.to_numeric(yearly_n["extent"], errors="coerce")
yearly_s["extent"] = pd.to_numeric(yearly_s["extent"], errors="coerce")

fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Arctic Sea Ice", "Antarctic Sea Ice"),
    specs=[[{"type": "geo"}, {"type": "geo"}]]
)

years = sorted(yearly_n["year"].unique())

for y in years:
    n_data = yearly_n[yearly_n["year"] == y]
    s_data = yearly_s[yearly_s["year"] == y]

    # 북극
    fig.add_trace(go.Scattergeo(
        lat=[82],
        lon=[0],
        mode="markers+text",
        text=[f"Arctic<br>{n_data['extent'].values[0]:.2f}"],
        textposition="bottom center",
        marker=dict(
            size=n_data["extent"].values[0] * 15,
            color="blue",
            opacity=0.7
        ),
        name=f"Arctic {y}",
        visible=False,
        showlegend=False
    ), row=1, col=1)

    # 남극
    fig.add_trace(go.Scattergeo(
        lat=[-82],
        lon=[0],
        mode="markers+text",
        text=[f"Antarctic<br>{s_data['extent'].values[0]:.2f}"],
        textposition="top center",
        marker=dict(
            size=s_data["extent"].values[0] * 15,
            color="cyan",
            opacity=0.7
        ),
        name=f"Antarctic {y}",
        visible=False,
        showlegend=False
    ), row=1, col=2)

# 첫 해만 보이게
fig.data[0].visible = True
fig.data[1].visible = True

steps = []
for i, y in enumerate(years):
    step = dict(
        method="update",
        args=[
            {"visible": [False] * len(fig.data)},
            {"title": f"Sea Ice Extent - {y}"}
        ],
        label=str(y)
    )
    step["args"][0]["visible"][i*2] = True
    step["args"][0]["visible"][i*2 + 1] = True
    steps.append(step)

sliders = [dict(
    active=0,
    steps=steps,
    currentvalue={"prefix": "Year: "}
)]

fig.update_geos(
    projection_type="orthographic",
    showland=True,
    landcolor="lightgray",
    oceancolor="lightblue",
    showcountries=True
)

fig.update_layout(
    title="Arctic & Antarctic Sea Ice Extent Over Time",
    sliders=sliders,
    height=500
)

fig.show()

fig2 = go.Figure()

fig2.add_trace(go.Scatter(
    x=yearly_n["year"],
    y=yearly_n["extent"],
    mode="lines+markers",
    name="Arctic",
    line=dict(color="blue", width=3),
    marker=dict(size=6)
))

fig2.add_trace(go.Scatter(
    x=yearly_s["year"],
    y=yearly_s["extent"],
    mode="lines+markers",
    name="Antarctic",
    line=dict(color="cyan", width=3),
    marker=dict(size=6)
))

fig2.update_layout(
    title="Sea Ice Extent Trends",
    xaxis_title="Year",
    yaxis_title="Ice Extent (million km²)",
    hovermode="x unified",
    template="plotly_white",
    height=500
)

fig2.show()

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# 데이터 로드 및 정리
temperature = pd.read_csv('/content/GLB.Ts+dSST.csv', header=1)
temperature = temperature.replace('***', pd.NA)
temperature['J-D'] = pd.to_numeric(temperature['J-D'], errors='coerce')
temperature_jd = temperature[['Year', 'J-D']].dropna()

fig = go.Figure()

fig.add_trace(go.Bar(
    x=temperature_jd['Year'],
    y=temperature_jd['J-D'],
    marker=dict(
        color=temperature_jd['J-D'],
        colorscale='RdBu_r',
        colorbar=dict(title='온도 편차 (°C)'),
        cmin=-0.5,
        cmax=1.5
    ),
    hovertemplate='연도: %{x}<br>온도 편차: %{y:.2f}°C<extra></extra>'
))

fig.add_hline(y=0, line_dash="solid", line_color="black", line_width=2)

fig.update_layout(
    title='온도 편차 시각화: 온난화 막대 그래프',
    xaxis_title='연도',
    yaxis_title='온도 편차 (°C)',
    template='plotly_white',
    height=500,
    font=dict(family="Arial, sans-serif")
)

fig.show()

fig2 = go.Figure()

# 원본 데이터 (연한 색)
fig2.add_trace(go.Scatter(
    x=temperature_jd['Year'],
    y=temperature_jd['J-D'],
    mode='lines',
    name='연간 데이터',
    line=dict(color='lightcoral', width=1),
    opacity=0.5
))

# 10년 이동평균
temperature_jd['MA_10'] = temperature_jd['J-D'].rolling(window=10, center=True).mean()

fig2.add_trace(go.Scatter(
    x=temperature_jd['Year'],
    y=temperature_jd['MA_10'],
    mode='lines',
    name='10년 이동평균',
    line=dict(color='darkred', width=4)
))

fig2.add_hline(y=0, line_dash="dot", line_color="gray")

fig2.update_layout(
    title='전지구 온도 편차 및 10년 이동평균',
    xaxis_title='연도',
    yaxis_title='온도 편차 (°C)',
    hovermode='x unified',
    template='plotly_white',
    height=600,
    font=dict(family="Arial, sans-serif")
)

fig2.show()

print("\n 온도 데이터 통계:")
print(f"데이터 범위: {temperature_jd['Year'].min():.0f}년 - {temperature_jd['Year'].max():.0f}년")
print(f"가장 추웠던 해: {temperature_jd.loc[temperature_jd['J-D'].idxmin(), 'Year']:.0f}년 ({temperature_jd['J-D'].min():.2f}°C)")
print(f"가장 더웠던 해: {temperature_jd.loc[temperature_jd['J-D'].idxmax(), 'Year']:.0f}년 ({temperature_jd['J-D'].max():.2f}°C)")
print(f"평균 온도 편차 (1880-2024): {temperature_jd['J-D'].mean():.2f}°C")
print(f"평균 온도 편차 (2000-2024): {temperature_jd[temperature_jd['Year'] >= 2000]['J-D'].mean():.2f}°C")

# 최근 10년 평균
recent_10 = temperature_jd.tail(10)['J-D'].mean()
print(f"최근 10년 평균: {recent_10:.2f}°C")

import pandas as pd
import plotly.graph_objects as go
import numpy as np

# 데이터 로드
sea_level = pd.read_csv('/content/GMSL_TPJAOS_5.2.txt', sep=r'\s+', header=None)
df_selected = sea_level.iloc[:, [2, 8]].copy()
df_selected.columns = ['year_fraction', 'GMSL_GIA']

# 연도를 정수로 변환
df_selected['year'] = df_selected['year_fraction'].astype(int)

fig1 = go.Figure()

# 실제 해수면 데이터
fig1.add_trace(go.Scatter(
    x=df_selected['year_fraction'],
    y=df_selected['GMSL_GIA'],
    mode='lines',
    name='해수면 높이',
    line=dict(color='rgb(37, 99, 235)', width=2),
    hovertemplate='연도: %{x:.2f}<br>해수면: %{y:.2f}mm<extra></extra>'
))

# 추세선
z = np.polyfit(df_selected['year_fraction'], df_selected['GMSL_GIA'], 1)
p = np.poly1d(z)
fig1.add_trace(go.Scatter(
    x=df_selected['year_fraction'],
    y=p(df_selected['year_fraction']),
    mode='lines',
    name=f'추세선 (연간 상승률: {z[0]:.2f}mm)',
    line=dict(color='darkblue', width=3, dash='dash')
))

fig1.update_layout(
    title='전지구 평균 해수면 변화 (1993-2025)<br><sub>위성 관측 데이터 (GIA 보정 적용)</sub>',
    xaxis_title='연도',
    yaxis_title='해수면 높이 (mm)',
    hovermode='x unified',
    template='plotly_white',
    height=600,
    font=dict(family="Arial, sans-serif")
)

fig1.show()

# 연평균 계산
yearly_avg = df_selected.groupby('year')['GMSL_GIA'].mean().reset_index()
yearly_avg['상승량'] = yearly_avg['GMSL_GIA'].diff()

fig2 = go.Figure()

fig2.add_trace(go.Bar(
    x=yearly_avg['year'],
    y=yearly_avg['상승량'],
    marker=dict(
        color=yearly_avg['상승량'],
        colorscale='Blues',
        colorbar=dict(title='상승량 (mm)')
    ),
    hovertemplate='연도: %{x}<br>전년 대비 상승: %{y:.2f}mm<extra></extra>'
))

fig2.update_layout(
    title='연간 해수면 상승량',
    xaxis_title='연도',
    yaxis_title='전년 대비 상승량 (mm)',
    template='plotly_white',
    height=500,
    font=dict(family="Arial, sans-serif")
)

fig2.show()

# 통계 정보
print("\n 해수면 변화 통계:")
print(f"데이터 범위: {df_selected['year_fraction'].min():.2f}년 - {df_selected['year_fraction'].max():.2f}년")
print(f"총 상승량: {df_selected['GMSL_GIA'].iloc[-1] - df_selected['GMSL_GIA'].iloc[0]:.2f}mm")
print(f"평균 상승 속도: {z[0]:.2f}mm/년")

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# 해수면 데이터
sea_level = pd.read_csv('/content/GMSL_TPJAOS_5.2.txt', sep=r'\s+', header=None)
df_sea = sea_level.iloc[:, [2, 8]].copy()
df_sea.columns = ['year_fraction', 'GMSL_GIA']

# 기온 데이터
temperature = pd.read_csv('/content/GLB.Ts+dSST.csv', header=1)
temperature = temperature.replace('***', pd.NA)
temperature['J-D'] = pd.to_numeric(temperature['J-D'], errors='coerce')
df_temp = temperature[['Year', 'J-D']].dropna()
df_temp.columns = ['year', 'temperature']

# 해빙 데이터 (북극 + 남극)
yearly_n = yearly_n.rename(columns=lambda x: x.strip())
yearly_s = yearly_s.rename(columns=lambda x: x.strip())
yearly_n["extent"] = pd.to_numeric(yearly_n["extent"], errors="coerce")
yearly_s["extent"] = pd.to_numeric(yearly_s["extent"], errors="coerce")

df_ice_n = yearly_n[['year', 'extent']].copy()
df_ice_n.columns = ['year', 'arctic']
df_ice_s = yearly_s[['year', 'extent']].copy()
df_ice_s.columns = ['year', 'antarctic']

df_ice = pd.merge(df_ice_n, df_ice_s, on='year')

# 공통 연도 범위 (1993-2024)
common_years = range(1993, 2025)

# 각 데이터를 공통 연도로 필터링
df_temp_common = df_temp[df_temp['year'].isin(common_years)]
df_sea_common = df_sea[(df_sea['year_fraction'] >= 1993) & (df_sea['year_fraction'] < 2025)]
df_ice_common = df_ice[df_ice['year'].isin(common_years)]

# 해수면 데이터를 연평균으로
df_sea_common['year'] = df_sea_common['year_fraction'].astype(int)
df_sea_yearly = df_sea_common.groupby('year')['GMSL_GIA'].mean().reset_index()

# 정규화 함수
def normalize(series):
    return (series - series.min()) / (series.max() - series.min()) * 100

# 데이터 병합
merged = df_temp_common.merge(df_sea_yearly, on='year')
merged = merged.merge(df_ice_common[['year', 'arctic', 'antarctic']], on='year')

# 정규화된 값 계산
temp_norm = normalize(df_temp_common['temperature'])
sea_norm = normalize(df_sea_yearly['GMSL_GIA'])
arctic_norm = 100 - normalize(df_ice_common['arctic'])  # 감소이므로 반전

fig = make_subplots(
    rows=1, cols=3,
    subplot_titles=(
        '기온 vs 해수면',
        '기온 vs 북극 해빙',
        '연도별 종합 변화율'
    ),
    specs=[[
        {"type": "scatter"},
        {"type": "scatter"},
        {"type": "bar"}
    ]],
    vertical_spacing=0.15,
    horizontal_spacing=0.12
)

# 1) 기온 vs 해수면 (산점도)
fig.add_trace(
    go.Scatter(
        x=merged['temperature'],
        y=merged['GMSL_GIA'],
        mode='markers',
        marker=dict(
            color=merged['year'],
            colorscale='Viridis',
            size=10,
            showscale=True,
            colorbar=dict(title="연도", x=1.05, len=0.6)
        ),
        text=merged['year'],
        hovertemplate='기온: %{x:.2f}°C<br>해수면: %{y:.2f}mm<br>연도: %{text}<extra></extra>'
    ),
    row=1, col=1
)

# 2) 기온 vs 북극 해빙 (산점도)
fig.add_trace(
    go.Scatter(
        x=merged['temperature'],
        y=merged['arctic'],
        mode='markers',
        marker=dict(
            color=merged['year'],
            colorscale='Plasma',
            size=10,
            showscale=False
        ),
        text=merged['year'],
        hovertemplate='기온: %{x:.2f}°C<br>북극: %{y:.2f} million km²<br>연도: %{text}<extra></extra>'
    ),
    row=1, col=2
)
# 4) 연도별 변화율 (바 차트)
merged['temp_change'] = merged['temperature'].diff()
merged['sea_change'] = merged['GMSL_GIA'].diff()
merged['ice_change'] = merged['arctic'].diff()

fig.add_trace(
    go.Bar(
        x=merged['year'],
        y=merged['temp_change'],
        name='기온 변화',
        marker_color='rgba(220, 38, 38, 0.7)',
        hovertemplate='연도: %{x}<br>전년 대비: %{y:.3f}°C<extra></extra>'
    ),
    row=1, col=3
)

# 레이아웃 설정
fig.update_xaxes(title_text="기온 편차 (°C)", row=1, col=1)
fig.update_yaxes(title_text="해수면 (mm)", row=1, col=1)
fig.update_xaxes(title_text="기온 편차 (°C)", row=1, col=2)
fig.update_yaxes(title_text="북극 해빙 (million km²)", row=1, col=2)
fig.update_xaxes(title_text="연도", row=2, col=1)
fig.update_yaxes(title_text="정규화 값 (0-100)", row=2, col=1)
fig.update_xaxes(title_text="연도", row=2, col=2)
fig.update_yaxes(title_text="전년 대비 변화 (°C)", row=2, col=2)

fig.update_layout(
    title_text='기후 변화 상관관계 분석 대시보드<br><sub>1993-2024년 데이터 기반</sub>',
    height=500,
    template='plotly_white',
    showlegend=True,
    font=dict(family="Arial, sans-serif"),
    hovermode='closest'
)

fig.show()

print("\n기후 변화 종합 통계 (1993-2024):")
print("\n 기온:")
print(f"  평균 상승: {df_temp_common['temperature'].mean():.2f}°C")
print(f"  최대값: {df_temp_common['temperature'].max():.2f}°C ({df_temp_common.loc[df_temp_common['temperature'].idxmax(), 'year']:.0f}년)")
print(f"  총 상승: {df_temp_common['temperature'].iloc[-1] - df_temp_common['temperature'].iloc[0]:.2f}°C")

print("\n 해수면:")
print(f"  총 상승: {df_sea_yearly['GMSL_GIA'].iloc[-1] - df_sea_yearly['GMSL_GIA'].iloc[0]:.2f}mm")
print(f"  연평균 상승률: {(df_sea_yearly['GMSL_GIA'].iloc[-1] - df_sea_yearly['GMSL_GIA'].iloc[0]) / len(df_sea_yearly):.2f}mm/년")

print("\n 북극 해빙:")
print(f"  총 감소: {df_ice_common['arctic'].iloc[0] - df_ice_common['arctic'].iloc[-1]:.2f} million km²")
print(f"  감소율: {((df_ice_common['arctic'].iloc[0] - df_ice_common['arctic'].iloc[-1]) / df_ice_common['arctic'].iloc[0] * 100):.1f}%")

print("\n 남극 해빙:")
print(f"  변화: {df_ice_common['antarctic'].iloc[-1] - df_ice_common['antarctic'].iloc[0]:.2f} million km²")

# 상관계수 계산
from scipy.stats import pearsonr

corr_temp_sea, p_temp_sea = pearsonr(merged['temperature'], merged['GMSL_GIA'])
corr_temp_ice, p_temp_ice = pearsonr(merged['temperature'], merged['arctic'])

print("\n 상관관계:")
print(f"  기온-해수면 상관계수: {corr_temp_sea:.3f} (p-value: {p_temp_sea:.4f})")
print(f"  기온-북극해빙 상관계수: {corr_temp_ice:.3f} (p-value: {p_temp_ice:.4f})")

import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

temp = pd.read_csv('/content/GLB.Ts+dSST.csv', header=1)

temp = temp.replace('***', pd.NA)
temp['J-D'] = pd.to_numeric(temp['J-D'], errors='coerce')

df = temp[['Year', 'J-D']].dropna()
df.columns = ['year', 'temp']

X = df[['year']]
y = df['temp']
model = LinearRegression().fit(X, y)

future_year = np.array([[2026]])
pred_2026 = model.predict(future_year)[0]
print("2026년 지구 평균 온도 예측:", pred_2026)

y_pred = model.predict(X)

sse = np.sum((y - y_pred)**2)

rmse = np.sqrt(np.mean((y - y_pred)**2))
n = len(y)
rse = np.sqrt(sse / (n - 2))

print("\n=== 모델 정확도 ===")
print("RMSE:", rmse)
print("RSE :", rse)